namn = input("Vad heter du?")
print("Hej", "Alice", "!")
favoritfärg= input("Vad är din favoritfärg")
print("Din favoritfärg är", favoritfärg)
print("vilken fin favoritfärg", namn)
mat=input("vilken typ av mat gillar du?")
print(namn, mat, "det låter gott")
pengar=input("hur mycket pengar har du på kontot?")
print(namn,"du är nästan miljonär")
